parameters:
  EnableCompliance:
  EnableAPIScan:

steps:
- task: MicroBuildCodesignVerify@3
  displayName: 🔍 Verify Signed Files
  inputs:
    ApprovalListPathForCerts: $(Build.SourcesDirectory)\azure-pipelines\no_authenticode.txt
    TargetFolders: |
      $(Build.SourcesDirectory)/bin/Packages/$(BuildConfiguration)/NuGet
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

- ${{ if eq(parameters.EnableCompliance, 'true') }}:
  - template: secure-development-tools.yml
    parameters:
      EnableAPIScan: ${{ parameters.EnableAPIScan }}
