trigger:
  batch: true
  branches:
    include:
    - main
    - 'v1*'
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
pr: none

variables:
  TreatWarningsAsErrors: true
  UpdateXlfOnBuild: false # force build breaks if xlf files aren't updated on dev box with resx changes
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
  NugetSecurityAnalysisWarningLevel: none # we use packages.lock.json to verify package content.

jobs:
- job: Windows
  pool: VSEngSS-MicroBuild2019-1ES
  steps:
  - template: build.yml
